# Generated by Django 5.1.7 on 2025-03-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.URLField(help_text='URL to the course image'),
        ),
        migrations.AlterField(
            model_name='course',
            name='video',
            field=models.URLField(help_text='URL to the course video'),
        ),
    ]
