name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        architecture: 'x64'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install django==5.1.7
        
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test

        - uses: actions/setup-python@v3
